apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: vcluster
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: vcluster.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: vcluster
        plural: vcluster
        singular: vcluster
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    namespace:
                      description: |
                        The name of the namespace to create vcluster in
                      type: string
                  type: object
              type: object
          served: true
          storage: true
  destinationSelectors:
  - matchLabels:
      environment: platform
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/vcluster-configure-pipeline:v0.1.0
                name: vcluster-configure-pipeline
