apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: vaultnamespace
  namespace: default
spec:
  clusterSelector:
    environment: platform
  workerClusterResources:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: vault-promise
        namespace: default
      rules:
      - apiGroups:
        - ""
        resourceNames:
        -  vault
        resources:
        - configmaps
        verbs:
        - get
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: vault-promise
        namespace: default
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: vault-promise
      subjects:
      - kind: ServiceAccount
        name: vaultnamespace-default-promise-pipeline
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: vault-client-auth-delegator
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:auth-delegator
      subjects:
      - kind: ServiceAccount
        name: vaultnamespace-default-promise-pipeline
        namespace: default
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: vaultnamespaces.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: VaultNamespace
        plural: vaultnamespaces
        singular: vaultnamespace
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  team:
                    description: The team name
                    type: string
                  kubernetes:
                    properties:
                      host:
                        description: kubernetes address
                        type: string
                      caCert:
                        description: kubernetse ca certificate
                        type: string
                    type: object
                required:
                  - team
                  - kubernetes
                type: object
            type: object
        served: true
        storage: true
  xaasRequestPipeline:
  - ghcr.io/syntasso/kratix-marketplace/vault-namespace-request-pipeline:v0.1.0
